### ISSUE TITLE
templateDirectoryLocation is not defined

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#495]
Hi,

I am wondering if you get this issue in your environments.

When it tries to render a forbidden page such as `default/rdmp/admin/users` when the user is not admin I get an error in rendering referring to:

```
warn: res.forbidden() :: When attempting to render error page view, an error occured (sending JSON instead).  Details:  { ReferenceError: /opt/redbox-portal/views/default/default/layout.ejs:61
 <div class="container">
  <div class="row" style="position:relative">
  >>  <%- superPartial("/layout/logo.ejs", branding, portal, true) %>
 <div class="col-sm-2 search-box">
<a href="<%= BrandingService.getBrandAndPortalPath(req) %>/getAdvice"><img src="<%= BrandingService.getBrandAndPortalPath(req) %>/images/help.png" alt="<%= TranslationService.t('help-alt-text') %>"/></a>
templateDirectoryLocation is not defined
```
Browsing: https://github.com/redbox-mint/redbox-portal/blob/88e79eb146cddcc4097f8d6acba9d3ca4ed63773/views/functions.ejs#L13

found no declaration. or it might come from somewhere else.

Thanks,
Moises

**Comment by andrewbrazzatti** [comment]
Thanks Moises. When a user tries to access a forbidden url, the app doesn't execute I was setting that templateDirectoryPath parameter. I've updated the code that does get called and it now renders.
