### ISSUE TITLE
RecordService.provideUserAccessAndRemovePendingAccess breaks app

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#501]
Hi,

Found out by doing Generate API Key (Key **is** saved); RecordService.provideUserAccessAndRemovePendingAccess runs breaking the app because brand is null: 

```
redboxportal_1  | TypeError: Cannot read property 'id' of null
redboxportal_1  |     at RecordTypes.get (/opt/redbox-portal/api/services/RecordTypesService.js:63:57)
redboxportal_1  |     at Object.wrapper [as get] (/opt/redbox-portal/node_modules/@sailshq/lodash/lib/index.js:3275:19)
redboxportal_1  |     at Records.updateMeta (/opt/redbox-portal/api/services/RecordsService.js:114:39)
redboxportal_1  |     at SafeSubscriber.metadataResponse.subscribe.metadata [as _next] (/opt/redbox-portal/api/services/RecordsService.js:447:22)
```

https://github.com/redbox-mint/redbox-portal/blob/75ba9cd6a6734c186586cd9c640d7d930d6a9cbc/typescript/api/services/RecordsService.ts#L542

brand is null when sending updateMeta breaking there after

**Comment by andrewbrazzatti** [comment]
Hey @moisbo 
I've pushed up a fix for this (https://github.com/redbox-mint/redbox-portal/commit/5c7246805212f3add04465fb80a120585b40f4d4).

Thanks
Andrew
