### ISSUE TITLE
Data Record: usability problem when adding attachments

### ISSUE THREAD

**Issue by sharynys** [redbox-mint/redbox-portal#516]
We have seen a few times where users upload attachments and then navigate away from the record without saving.  It's too common a mistake, so we need to autosave on return from having uploaded an attachment.

**Comment by sharynys** [comment]
At least a minimal fix would be to change the text of the "enter" button to "upload"

**Comment by andrewbrazzatti** [comment]
The forms now support warning the user if they have unsaved changes when they attempt to navigate away. This also works for uploaded attachments.
