### ISSUE TITLE
local account passwords accept weird characters but not at login

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#529]
When I tried to change a local account and generated a password with weird characters the password changes and updates, but the login does not accept it.

Found it the hard way 😭 but the encrypted password saved the day.

**Comment by moisbo** [comment]
Also noted that it does not update it every-time I create one and follow the validation requests.

**Comment by andrewbrazzatti** [comment]
Hey @moisbo,

Can you give us some examples of what sort of weird characters are causing the issue?

**Comment by moisbo** [comment]
Sure thing.

One example is

`My1$trongPassword!` 

Another is to do which passes validation, and should not.

`d42ae1d7-ef05-4532-b745-334a984465c5` 

Looking at the DB the password changes, sometimes. Just to note, this is the admin user changing it on itself. Does this special user cannot change its password?

Thanks!

**Comment by shilob** [comment]
@moisbo I've just pushed up a fix for this.

**Comment by shilob** [comment]
Also, we've used https://www.npmjs.com/package/owasp-password-strength-test this to validate passwords.

**Comment by moisbo** [comment]
Thanks!
