### ISSUE TITLE
Add ability to refresh data selector in data publication form

### ISSUE THREAD

**Issue by andrewbrazzatti** [redbox-mint/redbox-portal#554]
A data publication should be should be immutable but not until the record has moved to the published state. Currently, once you link a data record, it is not possible to update the list of attachments if they've changed in the data record even though the record is not yet published.

A refresh button should be added to allow the user to update the list with the latest attachments for all stages except published.

**Comment by sharynys** [comment]
I can actually achieve this by just reselecting the data record. The newly added files to the data record show up in the DP file selector
