### ISSUE TITLE
paging through a full list of RDMPs is very slow

### ISSUE THREAD

**Issue by sharynys** [redbox-mint/redbox-portal#647]
When listing all RDMPs and paging through them, each page load is very slow and (in Safari at least) there is no feedback mechanism to show that it is doing anything. Also it appears to get slower the further you get through the list. When trying to go from page 27 to 28 the response time was over 30 seconds and then i would get page 28, 29, 30 and back to 28 in quick succession.

**Comment by andrewbrazzatti** [comment]
Fixed in v2.0.0
