### ISSUE TITLE
Create Record metaMetadata field hardcoded to createdby admin

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#723]
Hi, I just wanted to ask if this is correct. Or if it has a purpose.

https://github.com/redbox-mint/redbox-portal/blob/5d6b5864dcca8caa763b9066ee87a4ab29e291c1/typescript/api/controllers/webservice/RecordController.ts#L315

Cheers,
Moises

**Comment by shilob** [comment]
Hi @moisbo, as we're using token authentication the username of the requester should be available, as is demonstrated here: https://github.com/redbox-mint/redbox-portal/blob/5d6b5864dcca8caa763b9066ee87a4ab29e291c1/typescript/api/controllers/webservice/RecordController.ts#L300

@andrewbrazzatti perhaps you can recall the reason this was hardcoded to 'admin'?

**Comment by moisbo** [comment]
Oh Ok, maybe then is non-issue but we can remove it?

**Comment by andrewbrazzatti** [comment]
No good reason to hardcode to admin and we can definitely change it.

**Comment by shilob** [comment]
@moisbo is your use case requiring the removal of this field or can we just set this to the username of the API user, i.e. `req.user.username`?

**Comment by moisbo** [comment]
Sorry, did not mean to remove the field but the "admin". Yes req.user.username is good. I think it only affects rest api users. The field is informative, correct? As in, we already have authorization

**Comment by shilob** [comment]
Yes, it's just informative.
