### ISSUE TITLE
Email message queue instructions/help

### ISSUE THREAD

**Issue by moisbo** [redbox-mint/redbox-portal#798]
Hi, currently sending emails is met with

```
 error: Unable to post message to message queue: [object Object]
```

And debugging **result** contains ` { success: false }` [EmailService.ts#L81](https://github.com/redbox-mint/redbox-portal/blob/86e3fba1d5cfc2c9a2596da19cb18bdf42474ebd/typescript/api/services/EmailService.ts#L81)

Where do we configure the email queues?

Thanks!

**Comment by andrewbrazzatti** [comment]
Thanks @moisbo. I've added nodemailer support to the EmailService. You can now configure transport options in the serverOptions section of the emailnotification.js
https://github.com/redbox-mint/redbox-portal/blob/master/config/emailnotification.js#L10
More info on the transport options possible are available here (SMTP and others)
https://nodemailer.com/smtp/
